name: learn-github-actions
on: [push]
jobs:
#   check-bats-version:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#       - run: sudo npm install -g bats
#       - run: bats -v
# # --- artifact ---
#   upload-file:
#     runs-on: ubuntu-latest
#     steps:
#     - name: create file
#       shell: bash
#       run: |
#         expr 1 + 1 > output.log
#     - name: upload file
#       uses: actions/upload-artifact@v2.2.4
#       with:
#         name: output-log-file
#         path: output.log
#   download-file:
#     runs-on: ubuntu-latest
#     needs: upload-file
#     steps:
#     - name: Download a single artifact
#       uses: actions/download-artifact@v2
#       with:
#         name: output-log-file
#     - name: view files
#       run: cat output.log
# # --- Secret ---
#   secret:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Retrieve secret
#       env:
#         super_secret: ${{ secrets.SUPERSECRET }}
#       run: |
#         if [ "$super_secret" == "Test1234" ]; then echo PASS; fi
#     - name: Finished Test1234
#       run: echo 'Test1234'
# # --- Dependency ---
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2.3.4
    - name: setup
      run: bash ./setup_server.sh setup
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2.3.4
    - name: build
      run: bash ./setup_server.sh build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2.3.4
    - name: test
      run: bash ./setup_server.sh test
