name: learn-github-actions
on: [push]
jobs:
#   check-bats-version:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#       - run: sudo npm install -g bats
#       - run: bats -v
  example-job:
    runs-on: ubuntu-latest
    steps:
    - name: Check out codes
      uses: actions/checkout@v2
#     - name: Connect to PostgreSQL
#       run: echo "POSTGRES_HOST=${POSTGRES_HOST}, POSTGRES_PORT=${POSTGRES_PORT}"
#       env:
#         POSTGRES_HOST: postgres
#         POSTGRES_PORT: 5432
#     - name: test PWD
#       run: echo $PWD; ls -la .github/scripts/; which
    - name: Run build script
      run: bash ./.github/scripts/build.sh
    - shell: bash
      run: |
        expr 1 + 1 > output.log
    - name: Upload output file
      uses: actions/upload-artifact@v2
      with:
        name: output-log-file
        path: output.log
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: output-log-file
    - name: view files
      run: |
        ls -l 
        cat output-log-file
        path: output.log
